---
- name: RKE2 server install / config / start / kubectl / useradd
  hosts: rke2-server
  become: true
  become_user: root

  vars_prompt:
  - name: 'username'
    prompt: "Provide user name to be used by kubectl"
    private: false
  
  tasks:

  - name: Download installer
    shell: curl -sfL https://get.rke2.io --output /tmp/install.sh

  - name: Check install.sh exist
    shell: ls -la /tmp | grep -i install
    register: result01
  
  - debug: var=result01.stdout_lines

  - name: Add execute for install.sh
    shell: chmod +x /tmp/install.sh

  - name: Install RKE2 server
    shell: INSTALL_RKE2_TYPE=server INSTALL_RKE2_CHANNEL=latest /tmp/install.sh

  - name: Remove install.sh
    file:
      path: "/tmp/install.sh"
      state: absent

  - name: Create rke2 directory
    shell: mkdir -p /etc/rancher/rke2

  - name: Copy config.yaml
    ansible.builtin.copy:
      src: templates/config_server.yaml
      dest: /etc/rancher/rke2/config.yaml

  - name: Add execute for config.yaml
    shell: chmod +x /etc/rancher/rke2/config.yaml

  - name: Check config.yaml exist
    shell: ls -la /etc/rancher/rke2/
    register: result02
  
  - debug: var=result02.stdout_lines

  - name: Start service rke2-server on server node
    ansible.builtin.systemd_service:
      name: rke2-server.service
      state: started
      enabled: true

  - name: Link kubectl
    shell: ln -s /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/

  - name: Reboot machine and send a message
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"

  - name: Check rke2 server is running
    shell: ps -ef | grep -i rke2
    register: result03
  
  - debug: var=result03.stdout_lines

  - name: Add read for rke2.yaml
    shell: chmod o+r /etc/rancher/rke2/rke2.yaml

  - name: copy script using jinja2
    template:
       src: templates/useradd_and_link.sh.j2
       dest: /tmp/useradd_and_link.sh
  
  - set_fact:
      username: "{{ username }}" 
  
  - name: execute script
    shell: "bash /tmp/useradd_and_link.sh"
  
  - name: check user
    shell: ls /home
    register: resul04
  - debug: var=resul04.stdout_lines

  - name: Remove useradd_and_link.sh
    file:
      path: "/tmp/useradd_and_link.sh"
      state: absent
